/*
  This is the file for action-creators
  Its main purpose is to:
    - Collate the various actions that are being dispatched in the app
*/

export const INCREMENT_REQUESTED = 'INCREMENT_REQUESTED';
export const INCREMENT = 'INCREMENT';
export const DECREMENT_REQUESTED = 'DECREMENT_REQUESTED';
export const DECREMENT = 'DECREMENT';
export const GET_QUOTE_REQUESTED = 'GET_QUOTE_REQUESTED';
export const GOT_QUOTE = 'GOT_QUOTE';

export const TOGGLE_ACTIVE_USER = 'TOGGLE_ACTIVE_USER';

export const FETCHING_STATIC_DATABASE = 'FETCHING_STATIC_DATABASE';
export const FETCHED_STATIC_DATABASE = 'FETCHED_STATIC_DATABASE';
export const FETCHING_STATIC_DATABASE_ERROR = 'FETCHING_STATIC_DATABASE_ERROR';

export const FETCHING_CHARTS_DATABASE = 'FETCHING_CHARTS_DATABASE';
export const FETCHED_CHARTS_DATABASE = 'FETCHED_CHARTS_DATABASE';
export const FETCHING_CHARTS_DATABASE_ERROR = 'FETCHING_CHARTS_DATABASE_ERROR';
